### ISSUE TITLE
bug in SAFETY comment?

### ISSUE THREAD

**Issue by evanrichter** [jonhoo/codecrafters-bittorrent-rust#1]
https://github.com/jonhoo/codecrafters-bittorrent-rust/blob/eac9d0701aa7af092fea6852e7e6ab4f77f7fd8f/src/main.rs#L127

should mention something about padding bytes as well, otherwise you could be reading uninitialized memory

```rs
// Safety: Handshake is a POD with repr(c) and contains no padding bytes between fields
```

I think in general, the technique of casting structs to bytes requires two things in rust:
- `#[repr(C)]` for consistent field ordering
- `#[repr(packed)]` to guarantee no between-field padding bytes

I *think* `Handshake` as written contains no padding bytes but I may be wrong.

**Comment by jonhoo** [comment]
Good catch, thanks!
